### ISSUE TITLE
Restrict enum34 dependency to python < 3.4

### ISSUE THREAD

**Issue by ABitMoreDepth** [pyinvoke/invocations#17]
Hi folks,

I recently migrated a python project from 3.4 to 3.6 and bumped into an issue caused by a dependency on enum34.

Having a dig around, that dependency is drawn from invocations itself, but is caused because the backport doesn't include features that the 3.6 enum stdlib does include.

Can we consider pinning the enum34 dependency to python <3.4?

**Comment by jefftriplett** [comment]
Related to #21 too.

**Comment by utapyngo** [comment]
I am not sure that this issue is resolved. The closed pull request is named "Only install enum34 on python2", and it does not seem to affect Python 3.

**Comment by bitprophet** [comment]
@utapyngo That PR tells packaging metadata (eg pip) to not even consider the enum34 dependency on python "< 3" - so it should cover this problem entirely. No Python 3 interpreters should install enum34 when installing the latest invocations release.

**Comment by utapyngo** [comment]
I see, thanks. This means that versions of Python 3 before 3.4 are not supported, right?

**Comment by bitprophet** [comment]
@utapyngo Correct, but those have not been supported anyways, so it's not a problem :)
